#!/usr/bin/env perl
use v5.34;
use warnings;

# PODNAME: watchman
# ABSTRACT: Watch out!
our $VERSION = '0.022'; # VERSION

use IO::Interactive qw( is_interactive );
use Log::Any::Adapter;
use Log::Any::Plugin;

use App::Watchman;

if (is_interactive()) {
    Log::Any::Adapter->set('Stdout');
    Log::Any::Plugin->add('Stringify');
    Log::Any::Plugin->add('Levels', level => 'info');
}

my $watchman = App::Watchman->new;
$watchman->run;

exit 0;

__END__

=pod

=encoding UTF-8

=head1 NAME

watchman - Watch out!

=head1 VERSION

version 0.022

=head1 AUTHOR

Stephen Thirlwall <sdt@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2016 by Stephen Thirlwall.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
